# Generated by Django 4.2.27 on 2025-12-06 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remaining_qty', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=64, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='product.product')),
            ],
            options={
                'db_table': 'stock_lots',
                'indexes': [models.Index(fields=['product', 'created_at'], name='stock_lots_product_d90ce3_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('reference_type', models.CharField(blank=True, max_length=64, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='product.product')),
            ],
            options={
                'db_table': 'inventory_transactions  ',
                'indexes': [models.Index(fields=['product'], name='inventory_t_product_c0453b_idx'), models.Index(fields=['-created_at'], name='inventory_t_created_4d81a5_idx'), models.Index(fields=['type'], name='inventory_t_type_473a11_idx')],
            },
        ),
    ]
