# Generated by Django 4.2.27 on 2025-12-25 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_qty', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=16)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('CONVERTED', 'CONVERTED')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
            options={
                'db_table': 'purchase_order_suggestions',
                'indexes': [models.Index(fields=['status', 'created_at'], name='purchase_or_status_269be5_idx'), models.Index(fields=['product'], name='purchase_or_product_6d9c34_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('minimum_order_qty', models.IntegerField(default=1)),
                ('lead_time_days', models.IntegerField(default=7)),
                ('is_preferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='product.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_products', to='supplier.supplier')),
            ],
            options={
                'db_table': 'product_suppliers',
                'indexes': [models.Index(fields=['product', 'is_preferred'], name='product_sup_product_4491ab_idx')],
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
